"""Where things live, resolved from the package rather than the CWD.

The API has to work when the process is started from another directory, from
a test runner, and from a serverless function whose working directory is not
the repo root. Every path in the app goes through here.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

POLICY = ROOT / "policy" / "authorize.yaml"
RESULTS = ROOT / "eval" / "results"
CALIBRATION = RESULTS / "calibration.json"
FAILURES = ROOT / "FAILURES.md"
TESTS = ROOT / "tests"
WEB = ROOT / "web"


BUILD = RESULTS / "build.json"


def test_count() -> int:
    """How many test CASES exist.

    Prefer the number `eval/build_manifest.py` generated by actually running
    pytest's collector, because reading the source counts test FUNCTIONS and a
    parametrised function is one function and many cases. Counting the source
    reported 372 while pytest collected 690, and the page published 372 under
    the label "tests". FAILURES #49.

    Reading the source stays as the fallback: a deployment carries the runtime,
    not the checkout, and a stale generated number is still better than a
    guessed one -- but a wrong-by-construction one is not.
    """
    try:
        import json
        d = json.loads(BUILD.read_text())
        n = d.get("test_cases") or d.get("tests")
        if n:
            return int(n)
    except Exception:
        pass
    n = 0
    try:
        for f in TESTS.glob("test_*.py"):
            n += f.read_text(encoding="utf-8").count("\ndef test_")
    except Exception:
        pass
    return n


def test_function_count() -> int:
    """Test functions defined in the source, which is not the number of cases."""
    n = 0
    try:
        for f in TESTS.glob("test_*.py"):
            n += f.read_text(encoding="utf-8").count("\ndef test_")
    except Exception:
        pass
    return n
