"""Where things live, resolved from the package rather than the CWD.

The API has to work when the process is started from another directory, from
a test runner, and from a serverless function whose working directory is not
the repo root. Every path in the app goes through here.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

POLICY = ROOT / "policy" / "authorize.yaml"
RESULTS = ROOT / "eval" / "results"
CALIBRATION = RESULTS / "calibration.json"
FAILURES = ROOT / "FAILURES.md"
TESTS = ROOT / "tests"
WEB = ROOT / "web"


BUILD = RESULTS / "build.json"


def test_count() -> int:
    """Count test functions by reading the files.

    Not by shelling out to pytest: that is slow, and in a serverless function
    it is impossible. Reading the source is honest and always available.
    """
    n = 0
    try:
        for f in TESTS.glob("test_*.py"):
            n += f.read_text(encoding="utf-8").count("\ndef test_")
    except Exception:
        pass
    if n:
        return n
    # A deployment carries the runtime, not the checkout. Fall back to the
    # count generated by eval/build_manifest.py rather than inventing one.
    try:
        import json
        return int(json.loads(BUILD.read_text())["tests"])
    except Exception:
        return 0
